spring:
  profiles:
    active: test
    #默认为开发环境

# 为 jasypt 配置解密秘钥
jasypt:
  encryptor:
    password: G0CvDz7oJn6

logging:
  path: /opt/logs/lilinjiashopping

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mySecret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24)
  tokenHead: Bearer  #JWT负载中拿到开头
mybatis:
  mapper-locations: classpath*:/mapping/*.xml
