spring:
  profiles:
    active: test
    #默认为开发环境

# 为 jasypt 配置解密秘钥
jasypt:
  encryptor:
    password: G0CvDz7oJn6

logging:
  path: /opt/logs/lilinjiashopping

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mySecret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24)
  tokenHead: Bearer  #JWT负载中拿到开头
mybatis:
  mapper-locations: classpath*:/mapping/*.xml
hymeleaf:
  prefix: classpath:/templates  #prefix：指定模板所在的目录
  check-template-location: true  #check-tempate-location: 检查模板路径是否存在
  cache: false  #cache: 是否缓存，开发模式下设置为false，避免改了模板还要重启服务器，线上设置为true，可以提高性能。
  suffix:  .html
  #encoding: UTF-8
  #content-type: text/html
  mode: HTML5
