spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #username: root
    #password: 123456
    username: ENC(D7QTSpYQOhgOQp3mVTjF0A==)
    password: ENC(sMvhmneq5uSmkogtV6P3Fg==)

    url: jdbc:mysql://47.114.52.253:3306/mall?useSSL=false&useUnicode=true&characterEncoding=utf-8&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    type: com.alibaba.druid.pool.DruidDataSource
server:
  port: 8902
